//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basenet.Educase.IdentityManager.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientToMandator
    {
        public System.Guid UID { get; set; }
        public System.Guid ClientUID { get; set; }
        public System.Guid MandatorUID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Mandator Mandator { get; set; }
    }
}
