//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basenet.Educase.IdentityManager.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeToClaim
    {
        public System.Guid UID { get; set; }
        public System.Guid ScopeUID { get; set; }
        public System.Guid ClaimUID { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual Scope Scope { get; set; }
    }
}
