//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basenet.Educase.IdentityManager.Facade.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basenet.Educase.IdentityManager.Facade.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} with the UID exists with another identifier {1}.
        /// </summary>
        internal static string The_Account_can_not_be_updated_with_the_identifyer {
            get {
                return ResourceManager.GetString("The_Account_can_not_be_updated_with_the_identifyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EmailAddress length exceeds 255..
        /// </summary>
        internal static string The_account_EmailAddress_length_exceed_maximum {
            get {
                return ResourceManager.GetString("The_account_EmailAddress_length_exceed_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Firstname length exceeds 100..
        /// </summary>
        internal static string The_account_Firstname_length_exceed_maximum {
            get {
                return ResourceManager.GetString("The_account_Firstname_length_exceed_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identifier {0} exists with another UID.
        /// </summary>
        internal static string The_account_Identifyer_already_exist {
            get {
                return ResourceManager.GetString("The_account_Identifyer_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identifier can not be null or empty..
        /// </summary>
        internal static string The_account_Identifyer_can_not_be_null_or_empty {
            get {
                return ResourceManager.GetString("The_account_Identifyer_can_not_be_null_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identifier length exceeds 255..
        /// </summary>
        internal static string The_account_Identifyer_length_exceed_maximum {
            get {
                return ResourceManager.GetString("The_account_Identifyer_length_exceed_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account {0} being updated that is not already assigned to the Tenant {1}..
        /// </summary>
        internal static string The_Account_is_not_already_assigned_to_the_Tenant_when_Update {
            get {
                return ResourceManager.GetString("The_Account_is_not_already_assigned_to_the_Tenant_when_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lastname length exceeds 100..
        /// </summary>
        internal static string The_account_Lastname_length_exceed_maximum {
            get {
                return ResourceManager.GetString("The_account_Lastname_length_exceed_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name can not be null or empty..
        /// </summary>
        internal static string The_account_Name_can_not_be_null_or_empty {
            get {
                return ResourceManager.GetString("The_account_Name_can_not_be_null_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name length exceeds 100..
        /// </summary>
        internal static string The_account_Name_length_exceed_maximum {
            get {
                return ResourceManager.GetString("The_account_Name_length_exceed_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ValidFrom is not allowed to be bigger than ValidTo..
        /// </summary>
        internal static string The_account_ValidFrom_is_not_allowed_to_be_bigger_than_ValidTo {
            get {
                return ResourceManager.GetString("The_account_ValidFrom_is_not_allowed_to_be_bigger_than_ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ValidFrom must have value if ValidTo is in the past..
        /// </summary>
        internal static string The_account_ValidFrom_must_have_value_if_validTo_is_in_the_past {
            get {
                return ResourceManager.GetString("The_account_ValidFrom_must_have_value_if_validTo_is_in_the_past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AccountUid can not be empty..
        /// </summary>
        internal static string The_AccountUid_can_not_be_empty {
            get {
                return ResourceManager.GetString("The_AccountUid_can_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MandatorUid can not be empty..
        /// </summary>
        internal static string The_MandatorUid_can_not_be_empty {
            get {
                return ResourceManager.GetString("The_MandatorUid_can_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tenant does not exist..
        /// </summary>
        internal static string The_Tenant_does_not_exist {
            get {
                return ResourceManager.GetString("The_Tenant_does_not_exist", resourceCulture);
            }
        }
    }
}
